import { useEffect, useState } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import toast from 'react-hot-toast';
import api, { errorMessage } from '../services/api';
import { useAuth } from '../context/AuthContext';
import { useCart } from '../context/CartContext';
import EmptyState from '../components/EmptyState';
import OrderTimeline from '../components/OrderTimeline';
import { PageLoader } from '../components/Loading';

const tabs=['Orders','Custom orders','Profile'];
export default function Account() {
  const {user,logout,setUser}=useAuth(); const {add}=useCart(); const nav=useNavigate(); const [tab,setTab]=useState('Orders'); const [orders,setOrders]=useState([]); const [requests,setRequests]=useState([]); const [loading,setLoading]=useState(true);
  const load=()=>Promise.all([api.get('/orders/mine'),api.get('/customizations/mine')]).then(([o,c])=>{setOrders(o.data.orders);setRequests(c.data.requests)}).catch(e=>toast.error(errorMessage(e))).finally(()=>setLoading(false));
  useEffect(()=>{load()},[]); const signout=()=>{logout();nav('/')};
  if(loading)return <PageLoader/>;
  return <section className="container-page py-12"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-sm font-bold uppercase tracking-widest text-clay">Your account</p><h1 className="mt-2 text-5xl">Hello, {user.fullName.split(' ')[0]}.</h1></div><button onClick={signout} className="btn-secondary">Logout</button></div><div className="mt-10 flex gap-2 overflow-x-auto border-b border-sand">{tabs.map(t=><button key={t} onClick={()=>setTab(t)} className={`whitespace-nowrap border-b-2 px-4 py-3 font-semibold ${tab===t?'border-clay text-clay':'border-transparent'}`}>{t}</button>)}</div><div className="mt-8">{tab==='Orders'&&<Orders orders={orders}/>} {tab==='Custom orders'&&<CustomOrders requests={requests} add={add} reload={load}/>} {tab==='Profile'&&<Profile user={user} setUser={setUser}/>}</div></section>;
}
function Orders({orders}) { if(!orders.length)return <EmptyState title="No orders yet" text="Your order history will appear here." action={<Link to="/shop" className="btn-primary">Start shopping</Link>}/>; return <div className="grid gap-5">{orders.map(o=><article key={o._id} className="card p-5 sm:p-7"><div className="flex flex-wrap justify-between gap-3"><div><p className="text-xs uppercase tracking-widest text-ink/50">Order number</p><h2 className="mt-1 text-xl">{o.orderNumber}</h2><p className="mt-1 text-sm text-ink/55">{new Date(o.createdAt).toLocaleDateString('en-IN',{dateStyle:'medium'})}</p></div><div className="text-right"><span className="rounded-full bg-blush px-3 py-1 text-sm font-semibold capitalize">{o.status}</span><p className="mt-2 text-lg font-bold">₹{o.total.toLocaleString('en-IN')}</p></div></div><div className="mt-5 flex gap-3 overflow-x-auto">{o.items.map((i,index)=><div key={index} className="flex min-w-52 items-center gap-3 rounded-xl bg-cream p-3"><img src={i.image} className="h-12 w-12 rounded-lg object-cover"/><div><p className="line-clamp-1 text-sm font-semibold">{i.name}</p><p className="text-xs text-ink/50">Qty {i.quantity}</p></div></div>)}</div><OrderTimeline status={o.status}/></article>)}</div> }
function CustomOrders({requests,add,reload}) {
  if(!requests.length)return <EmptyState title="No custom requests" text="Open any product and choose “Customize this product” to begin." action={<Link to="/shop" className="btn-primary">Browse products</Link>}/>;
  const decline=async id=>{try{await api.patch(`/customizations/${id}/decline`);toast.success('Quote declined');reload()}catch(e){toast.error(errorMessage(e))}};
  const accept=async r=>{if(await add(r.product._id,1,r._id))reload()};
  return <div className="grid gap-5">{requests.map(r=><article key={r._id} className="card grid gap-5 p-5 sm:grid-cols-[120px_1fr] sm:p-6"><img src={r.referenceImage.url} className="aspect-square w-full rounded-xl object-cover"/><div><div className="flex flex-wrap items-start justify-between gap-2"><div><p className="text-xs font-bold uppercase tracking-widest text-clay">{r.product?.name}</p><h2 className="mt-1 text-2xl">Customization request</h2></div><span className={`rounded-full px-3 py-1 text-sm font-semibold capitalize ${r.status==='approved'?'bg-green-100 text-green-800':r.status==='rejected'||r.status==='declined'?'bg-red-100 text-red-800':'bg-blush'}`}>{r.status}</span></div><p className="mt-3 text-sm leading-6 text-ink/65">{r.description}</p>{r.adminNote&&<p className="mt-3 rounded-lg bg-cream p-3 text-sm"><strong>Studio note:</strong> {r.adminNote}</p>}{r.status==='approved'&&<div className="mt-5 flex flex-wrap items-center justify-between gap-3"><p className="text-xl font-bold">Quoted price: ₹{r.customPrice.toLocaleString('en-IN')}</p><div className="flex gap-2"><button onClick={()=>decline(r._id)} className="btn-secondary">Reject</button><button onClick={()=>accept(r)} className="btn-primary">Accept & add to cart</button></div></div>}</div></article>)}</div>;
}
function Profile({user,setUser}) {
  const [form,setForm]=useState({fullName:user.fullName,address:user.address,phone:user.phone||''}); const [busy,setBusy]=useState(false);
  const submit=async e=>{e.preventDefault();setBusy(true);try{const {data}=await api.patch('/auth/me',form);setUser(data.user);localStorage.setItem('user',JSON.stringify(data.user));toast.success('Profile updated')}catch(err){toast.error(errorMessage(err))}finally{setBusy(false)}};
  return <form onSubmit={submit} className="card max-w-2xl space-y-5 p-6 sm:p-8"><h2 className="text-2xl">Profile information</h2><div><label className="label">Full name</label><input required value={form.fullName} onChange={e=>setForm({...form,fullName:e.target.value})}/></div><div><label className="label">Email</label><input disabled value={user.email} className="opacity-60"/></div><div><label className="label">Phone number</label><input value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})}/></div><div><label className="label">Saved address</label><textarea required rows="4" value={form.address} onChange={e=>setForm({...form,address:e.target.value})}/></div><button disabled={busy} className="btn-primary">{busy?'Saving…':'Save profile'}</button></form>;
}
