import { useState } from 'react';
import { Link } from 'react-router-dom';
import { Minus, Plus, Trash2 } from 'lucide-react';
import { useCart } from '../context/CartContext';
import EmptyState from '../components/EmptyState';
import ConfirmDialog from '../components/ConfirmDialog';
import { PageLoader } from '../components/Loading';

export default function Cart() {
  const {cart,loading,update,remove}=useCart(); const [removeId,setRemoveId]=useState(null);
  if(loading)return <PageLoader/>;
  if(!cart.items.length)return <section className="container-page py-16"><EmptyState title="Your cart is waiting" text="Find something handmade that speaks to you." action={<Link to="/shop" className="btn-primary">Explore crafts</Link>}/></section>;
  return <section className="container-page py-12"><h1 className="text-5xl">Your cart</h1><div className="mt-10 grid items-start gap-8 lg:grid-cols-[1fr_380px]"><div className="grid gap-4">{cart.items.map(item=><div key={item.id} className="card flex gap-4 p-4 sm:p-5"><img src={item.customization?.referenceImage?.url||item.product.images?.[0]?.url} className="h-24 w-24 rounded-xl bg-blush object-cover sm:h-32 sm:w-32"/><div className="min-w-0 flex-1"><p className="text-xs font-bold uppercase tracking-wide text-clay">{item.customization?'Custom piece':item.product.category}</p><h2 className="mt-1 truncate text-xl">{item.customization?'Custom ':''}{item.product.name}</h2><p className="mt-1 font-semibold">₹{item.price.toLocaleString('en-IN')}</p><div className="mt-4 flex items-center justify-between"><div className="flex items-center rounded-full border border-sand"><button disabled={Boolean(item.customization)} onClick={()=>update(item.id,Math.max(1,item.quantity-1))} className="p-2"><Minus size={14}/></button><span className="w-8 text-center text-sm">{item.quantity}</span><button disabled={Boolean(item.customization)} onClick={()=>update(item.id,item.quantity+1)} className="p-2"><Plus size={14}/></button></div><button onClick={()=>setRemoveId(item.id)} className="p-2 text-red-700" aria-label="Remove"><Trash2 size={18}/></button></div></div></div>)}</div><aside className="card sticky top-28 p-6"><h2 className="text-2xl">Order summary</h2><div className="mt-6 flex justify-between text-ink/60"><span>Subtotal</span><span>₹{cart.subtotal.toLocaleString('en-IN')}</span></div><div className="mt-3 flex justify-between text-ink/60"><span>Delivery</span><span>Free</span></div><div className="my-5 border-t border-sand/50"/><div className="flex justify-between text-xl font-bold"><span>Total</span><span>₹{cart.total.toLocaleString('en-IN')}</span></div><Link to="/checkout" className="btn-primary mt-6 w-full">Proceed to checkout</Link><p className="mt-3 text-center text-xs text-ink/50">Cash on delivery only</p></aside></div><ConfirmDialog open={Boolean(removeId)} title="Remove this item?" text="You can always add it again later." onClose={()=>setRemoveId(null)} onConfirm={()=>{remove(removeId);setRemoveId(null)}}/></section>;
}
