import { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import { Heart, PackageCheck, Palette } from 'lucide-react';
import api from '../services/api';
import ProductCard from '../components/ProductCard';
import { ProductSkeleton } from '../components/Loading';

export default function Home() {
  const [products,setProducts]=useState([]); const [loading,setLoading]=useState(true);
  useEffect(()=>{api.get('/products?featured=true&limit=4').then(r=>setProducts(r.data.products)).finally(()=>setLoading(false));},[]);
  return <><section className="overflow-hidden bg-blush/45"><div className="container-page grid min-h-[620px] items-center gap-12 py-16 lg:grid-cols-2"><div><p className="mb-5 text-sm font-bold uppercase tracking-[.25em] text-clay">Crafted by hand · Kept by heart</p><h1 className="max-w-2xl text-5xl leading-[1.05] sm:text-6xl lg:text-7xl">Gifts that feel unmistakably personal.</h1><p className="mt-6 max-w-xl text-lg leading-8 text-ink/65">Discover handcrafted candles, resin keepsakes, delicate accessories, and custom pieces created around your story.</p><div className="mt-8 flex flex-wrap gap-3"><Link className="btn-primary" to="/shop">Explore the collection</Link><Link className="btn-secondary" to="/shop?category=Resin%20Works">See custom keepsakes</Link></div></div><div className="relative mx-auto aspect-square w-full max-w-lg rounded-[40%_60%_55%_45%] bg-gradient-to-br from-sand to-clay/60 shadow-soft"><div className="absolute inset-8 grid place-items-center rounded-[55%_45%_35%_65%] border border-white/40 bg-white/20 text-center"><div><Heart className="mx-auto text-white" size={70} strokeWidth={1}/><p className="mt-4 font-display text-3xl text-white">Made for your moments</p></div></div></div></div></section><section className="container-page py-20"><div className="mb-10 flex items-end justify-between"><div><p className="text-sm font-bold uppercase tracking-widest text-clay">Curated favourites</p><h2 className="mt-2 text-4xl">Made to be remembered</h2></div><Link to="/shop" className="hidden font-semibold underline sm:block">View all</Link></div><div className="grid gap-8 sm:grid-cols-2 lg:grid-cols-4">{loading?Array.from({length:4},(_,i)=><ProductSkeleton key={i}/>):products.map(p=><ProductCard key={p._id} product={p}/>)}</div></section><section className="bg-white py-20"><div className="container-page grid gap-10 md:grid-cols-3">{[[Palette,'Personal by design','Request colours, details, and a reference for a one-of-one piece.'],[Heart,'Made slowly','Every item carries the touch and character of genuine handwork.'],[PackageCheck,'Simple COD','Place your order securely and pay when it reaches your doorstep.']].map(([Icon,title,text])=><div key={title} className="text-center"><Icon className="mx-auto text-clay" size={34}/><h3 className="mt-4 text-2xl">{title}</h3><p className="mx-auto mt-2 max-w-sm text-ink/60">{text}</p></div>)}</div></section></>;
}
