import { useEffect, useState } from 'react';
import { useNavigate, useParams } from 'react-router-dom';
import { Minus, Plus, Sparkles } from 'lucide-react';
import toast from 'react-hot-toast';
import api, { errorMessage } from '../services/api';
import { useAuth } from '../context/AuthContext';
import { useCart } from '../context/CartContext';
import { PageLoader } from '../components/Loading';

export default function ProductDetail() {
  const {id}=useParams(); const nav=useNavigate(); const {user}=useAuth(); const {add}=useCart(); const [product,setProduct]=useState(null); const [image,setImage]=useState(''); const [qty,setQty]=useState(1); const [custom,setCustom]=useState(false);
  useEffect(()=>{api.get(`/products/${id}`).then(r=>{setProduct(r.data.product);setImage(r.data.product.images?.[0]?.url)}).catch(e=>{toast.error(errorMessage(e));nav('/shop')});},[id]);
  if(!product)return <PageLoader/>;
  const addItem=()=>user?add(product._id,qty):nav('/login',{state:{from:{pathname:location.pathname}}});
  return <section className="container-page py-12"><div className="grid gap-12 lg:grid-cols-2"><div><div className="overflow-hidden rounded-3xl bg-blush"><img src={image||'https://placehold.co/900x900/ead6ce/2f2925?text=Handmade'} alt={product.name} className="aspect-square w-full object-cover"/></div>{product.images.length>1&&<div className="mt-4 flex gap-3 overflow-x-auto">{product.images.map(i=><button key={i.url} onClick={()=>setImage(i.url)} className={`overflow-hidden rounded-xl border-2 ${image===i.url?'border-clay':'border-transparent'}`}><img src={i.url} className="h-20 w-20 object-cover"/></button>)}</div>}</div><div className="lg:py-8"><p className="text-sm font-bold uppercase tracking-widest text-clay">{product.category}{product.subcategory&&` · ${product.subcategory}`}</p><h1 className="mt-3 text-5xl leading-tight">{product.name}</h1><p className="mt-5 text-2xl font-semibold">₹{product.price.toLocaleString('en-IN')}</p><p className="mt-6 whitespace-pre-line leading-7 text-ink/65">{product.description}</p><p className={`mt-5 text-sm font-semibold ${product.stock?'text-sage':'text-red-700'}`}>{product.stock?`${product.stock} available`:'Currently out of stock'}</p><div className="mt-8 flex flex-wrap gap-3"><div className="flex items-center rounded-full border border-sand bg-white"><button className="p-3" onClick={()=>setQty(Math.max(1,qty-1))}><Minus size={17}/></button><span className="w-10 text-center font-semibold">{qty}</span><button className="p-3" onClick={()=>setQty(Math.min(product.stock,qty+1))}><Plus size={17}/></button></div><button disabled={!product.stock} onClick={addItem} className="btn-primary flex-1">Add to cart</button></div><button onClick={()=>user?setCustom(true):nav('/login',{state:{from:{pathname:location.pathname}}})} className="btn-secondary mt-4 w-full"><Sparkles size={18}/> Customize this product</button><div className="mt-8 rounded-2xl bg-white p-5 text-sm leading-6 text-ink/60"><strong className="text-ink">How customization works:</strong> Share your idea and one reference image. We will review it and send a fixed quote to your account. Accept it to add the custom piece to your cart.</div></div></div>{custom&&<CustomizationModal product={product} close={()=>setCustom(false)}/>}</section>;
}
function CustomizationModal({product,close}) {
  const [description,setDescription]=useState(''); const [file,setFile]=useState(null); const [busy,setBusy]=useState(false);
  const submit=async e=>{e.preventDefault();setBusy(true);const form=new FormData();form.append('productId',product._id);form.append('description',description);form.append('referenceImage',file);try{await api.post('/customizations',form);toast.success('Customization request submitted');close();}catch(err){toast.error(errorMessage(err));}finally{setBusy(false)}};
  return <div className="fixed inset-0 z-[70] grid place-items-center overflow-y-auto bg-ink/60 p-4" onMouseDown={close}><div className="card my-8 w-full max-w-xl p-7" onMouseDown={e=>e.stopPropagation()}><h2 className="text-3xl">Customize {product.name}</h2><p className="mt-2 text-sm text-ink/60">Describe colours, names, size, or details that matter to you.</p><form onSubmit={submit} className="mt-6 grid gap-4"><div><label className="label">Your customization description</label><textarea rows="6" minLength="10" maxLength="2000" required value={description} onChange={e=>setDescription(e.target.value)}/></div><div><label className="label">Reference image (JPG, PNG, or WebP, max 5MB)</label><input type="file" accept="image/jpeg,image/png,image/webp" required onChange={e=>setFile(e.target.files[0])}/></div><div className="flex justify-end gap-3"><button type="button" className="btn-secondary" onClick={close}>Cancel</button><button disabled={busy} className="btn-primary">{busy?'Submitting…':'Submit request'}</button></div></form></div></div>;
}
