import { Router } from 'express';
import { listProducts, getProduct, createProduct, updateProduct, deleteProduct } from '../controllers/productController.js';
import { protect, adminOnly } from '../middleware/auth.js';
import { upload } from '../middleware/upload.js';
const router = Router();
router.get('/', listProducts); router.get('/:id', getProduct);
router.post('/', protect, adminOnly, upload.array('images', 8), createProduct);
router.patch('/:id', protect, adminOnly, upload.array('images', 8), updateProduct);
router.delete('/:id', protect, adminOnly, deleteProduct);
export default router;
