import { useState } from 'react';
import { Link, NavLink, Outlet } from 'react-router-dom';
import { Menu, ShoppingBag, UserRound, X } from 'lucide-react';
import { useAuth } from '../context/AuthContext';
import { useCart } from '../context/CartContext';

const links = [['Shop','/shop'], ['Candles','/shop?category=Candles'], ['Resin Works','/shop?category=Resin%20Works'], ['Accessories','/shop?category=Accessories']];
export default function Layout() {
  const [open, setOpen] = useState(false); const { user } = useAuth(); const { count } = useCart();
  return <div className="min-h-screen"><div className="bg-ink py-2 text-center text-xs tracking-wide text-white">Handmade with heart · Cash on delivery across India</div><header className="sticky top-0 z-40 border-b border-sand/40 bg-cream/95 backdrop-blur"><div className="container-page flex h-20 items-center justify-between"><button className="md:hidden" onClick={()=>setOpen(!open)}>{open?<X/>:<Menu/>}</button><Link to="/" className="font-display text-2xl font-bold tracking-tight">The Gifter<span className="text-clay">.</span></Link><nav className="hidden items-center gap-7 md:flex">{links.map(([name,to])=><NavLink key={name} to={to} className="text-sm font-medium hover:text-clay">{name}</NavLink>)}</nav><div className="flex items-center gap-4"><Link to={user ? '/account' : '/login'} aria-label="Account"><UserRound size={21}/></Link><Link to="/cart" aria-label="Cart" className="relative"><ShoppingBag size={21}/>{count>0&&<span className="absolute -right-3 -top-3 grid h-5 min-w-5 place-items-center rounded-full bg-clay px-1 text-[10px] text-white">{count}</span>}</Link></div></div>{open&&<nav className="container-page grid gap-1 border-t border-sand/40 py-4 md:hidden">{links.map(([name,to])=><Link key={name} to={to} onClick={()=>setOpen(false)} className="rounded-lg px-3 py-3 hover:bg-blush/40">{name}</Link>)}</nav>}</header><main><Outlet/></main><footer className="mt-20 bg-ink py-14 text-white"><div className="container-page grid gap-10 md:grid-cols-3"><div><p className="font-display text-2xl">The Gifter.</p><p className="mt-3 max-w-xs text-sm text-white/60">Small-batch crafts made slowly, thoughtfully, and especially for you.</p></div><div><p className="font-semibold">Explore</p><div className="mt-3 grid gap-2 text-sm text-white/60"><Link to="/shop">All crafts</Link><Link to="/account">My account</Link><Link to="/cart">Your cart</Link></div></div><div><p className="font-semibold">A little note</p><p className="mt-3 text-sm text-white/60">Handmade pieces can have tiny variations. That is part of their charm.</p></div></div><div className="container-page mt-12 border-t border-white/10 pt-6 text-xs text-white/40">© {new Date().getFullYear()} The Gifter. All rights reserved.</div></footer></div>;
}
